name: Reusable workflow example

on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
    create-cluster:
        runs-on: ubuntu-latest
        steps:
          - name: Create k8s Kind Cluster
            uses: helm/kind-action@v1